### ISSUE TITLE
m

### ISSUE THREAD

**Issue by yasmasdas** [root-cause/v-decompiled-scripts#2]
theres alot of script missing 
some of them examples
fm_content_acid_lab_setup
fm_content_acid_lab_source
fm_content_acid_lab_sell
fm_content_drug_lab_work
fm_content_stash_house
fm_content_taxi_driver
fm_content_xmas_mugger
fm_content_bank_shootout
am_mp_acid_lab

**Comment by root-cause** [comment]
I'm confused, the examples you listed are all in the repo:

https://github.com/root-cause/v-decompiled-scripts/blob/master/fm_content_acid_lab_setup.c
https://github.com/root-cause/v-decompiled-scripts/blob/master/fm_content_acid_lab_source.c
...
https://github.com/root-cause/v-decompiled-scripts/blob/master/fm_content_bank_shootout.c
https://github.com/root-cause/v-decompiled-scripts/blob/master/am_mp_acid_lab.c

However GitHub truncates the list of files because there's too many of them, I recommend cloning the repo or using the download ZIP button.

**Comment by yasmasdas** [comment]
I did use clone but it didnt download them. it did now work after do it again
